apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: ncai-wbl-vlm-stage1-megatron-job
  namespace: p-ncai-etri-wbl
spec:
  # elastic은 유지하되, 여기서는 자동 학습 시작 안 하므로 단지 파드 생성을 위해 사용
  elasticPolicy:
    rdzvId: ncai-wbl-vlm-stage1-megatron
    rdzvBackend: c10d
    minReplicas: 8
    maxReplicas: 8
  nprocPerNode: "8"
  runPolicy:
    cleanPodPolicy: None
    schedulingPolicy:
      minAvailable: 1
  pytorchReplicaSpecs:
    Worker:
      replicas: 8
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"  # Istio sidecar injection 비활성화는 필수
        spec:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          nodeSelector:
            mlx.navercorp.com/zone: h100-i001v8
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  preference:
                    matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: NotIn
                        values:
                          - h100-i001v8-w-05fe
                      - key: kubernetes.io/hostname
                        operator: NotIn
                        values:
                          - h100-i001v8-w-016a
          imagePullSecrets:
            - name: ncai-wbl-registry-secret  # 프로젝트에 해당되는 Image Pull Secret 명
          # 서로 다른 노드로 분산 배치 추천(원하면 주석 해제)
          # affinity:
          #   podAntiAffinity:
          #     preferredDuringSchedulingIgnoredDuringExecution:
          #       - weight: 100
          #         podAffinityTerm:
          #           labelSelector:
          #             matchExpressions:
          #               - key: app
          #                 operator: In
          #                 values: ["dev-wbl-megatron"]
          #           topologyKey: "kubernetes.io/hostname"
          containers:
          - name: pytorch   # PyTorchJob은 컨테이너 이름 'pytorch' 권장
            image: ncai-wbl-registry.kr.ncr.ntruss.com/wbl-megatron-etri-ngc-py2506:0.6
            imagePullPolicy: IfNotPresent
            securityContext:  # Infiniband 를 사용하기 위한 securityContext가 필요합니다.
              capabilities:
                add: ["IPC_LOCK"]
            command: ["bash", "-lc"]
            args:
            - |
              set -euo pipefail

              export CUDA_DEVICE_MAX_CONNECTIONS=1

              pip install qwen_vl_utils

              # ==== 경로(필요시 수정) ====
              cd /mnt/output/ncai/multi_modal/Megatron-LM

              TM=$(date "+%Y-%m-%d_%H:%M:%S")

              TRAINING_PATH=/mnt/output/ncai/multi_modal/Megatron-LM
              MEGATRON_PATH="${TRAINING_PATH%/}megatron"

              DATA_PATH="${TRAINING_PATH}/vlm/stage_1_dataset.yaml"
              TOKENIZER_PATH="${TRAINING_PATH}/tokenizers/wbl_mm_tokenizer_v3"
              CHECKPOINT_PATH="${TRAINING_PATH}/checkpoints/vlm_merged_wbl_llm_sft_lr_3e6_seqlen_16384_iter_0008300"

              TP=1
              PP=1
              SEQ_LEN=4096
              MBS=8
              GBS=512
              # NSTEP=8720
              NSAMPLES=2100000     # 558128

              DEFAULT_OUTPUT_DIR="/mnt/output/ncai/multi_modal/outputs/vlm_stage_1"
              JOB_NAME="rice_gpt_stage_1_7b_a1b_gbs_${GBS}_no_moe_loss_finevision_data__llm_sft_lr_3e6_seqlen_16384_iter_0008300"

              SAVE_CKPT_PATH="${DEFAULT_OUTPUT_DIR}/checkpoints/${JOB_NAME}"
              TENSORBOARD_PATH="${DEFAULT_OUTPUT_DIR}/tensorboards/${JOB_NAME}"

              mkdir -p "$SAVE_CKPT_PATH"
              mkdir -p "$TENSORBOARD_PATH"
              mkdir -p "$SAVE_CKPT_PATH/dataloader"

              DISTRIBUTED_ARGS=(
                  --nproc_per_node ${PET_NPROC_PER_NODE}
                  --nnodes ${PET_NNODES}
                  --rdzv_id ${PET_RDZV_ID}
                  --rdzv_backend ${PET_RDZV_BACKEND}
                  --rdzv_endpoint ${PET_RDZV_ENDPOINT}
                  --rdzv-conf="timeout=6000"
              )

              MODEL_ARGS=(
                  --model-name rice-gpt-7b-a1b
                  --disable-bias-linear
                  --seq-length "${SEQ_LEN}"
                  --decoder-seq-length "${SEQ_LEN}"
                  --max-position-embeddings 32768
                  --num-layers 24
                  --position-embedding-type none
                  --hidden-size 1536
                  --ffn-hidden-size 5760
                  --num-attention-heads 12
                  --init-method-std 0.0134
                  --attention-dropout 0.0
                  --hidden-dropout 0.0
                  --swiglu
                  --untie-embeddings-and-output-weights
                  --no-masked-softmax-fusion
              )

              # --moe-ffn-hidden-size는 세팅하지 않는다. ffn-hidden-size를 따라감.
              #--moe-use-upcycling
              MOE_ARGS=(
                  --num-experts 64
                  --moe-layer-freq '([0]*1+[1]*23)'
                  --moe-ffn-hidden-size 960
                  --moe-shared-expert-intermediate-size 960 
                  --moe-router-load-balancing-type global_aux_loss
                  --moe-router-topk 5
                  --moe-grouped-gemm
                  --moe-aux-loss-coeff 0.
                  --moe-z-loss-coeff 0.
                  --moe-router-topk-scaling-factor 1.0
                  --moe-router-score-function 'sigmoid'
                  --moe-token-dispatcher-type alltoall
                  --moe-permute-fusion
                  --moe-router-dtype fp32
                  --overlap-param-gather
                  --overlap-grad-reduce
              )

              # YaRN을 사용하지 않으므로 mscale을 넣지 않는다.
              #    --mscale 1.0
              #    --mscale-all-dim 1.0
              MLA_ARGS=(
                  --multi-latent-attention
                  --q-lora-rank 768 # 768
                  --kv-lora-rank 512 # 768
                  --qk-head-dim 128 
                  --qk-pos-emb-head-dim 64
                  --v-head-dim 128
                  --rotary-scaling-factor 1.0
                  --normalization RMSNorm
                  --rope-type rope
                  --apply-layernorm-1p
                  --rotary-base 10000
                  --rotary-base-global 1000000
                  --qk-layernorm
              )

              DATA_ARGS=(
                  --tokenizer-type HuggingFaceTokenizer
                  --hf-tokenizer-path "$TOKENIZER_PATH"
                  --data-path "$DATA_PATH"
                  --dataloader-type external
                  --split 100,0,0
                  --num-workers 16
                  --chat-template rice-gpt
              )

              TRAINING_ARGS=(
                  --training-phase pretrain
                  --trainable-modules vision_projection
                  --micro-batch-size "${MBS}"
                  --global-batch-size "${GBS}"
                  --lr 1.0e-4
                  --min-lr 1.0e-6
                  --clip-grad 1.0
                  --weight-decay 0
                  --optimizer adam
                  --adam-beta1 0.9
                  --adam-beta2 0.99
                  --adam-eps 1e-05
                  --norm-epsilon 1e-6
                  # --train-iters "${NSTEP}"
                  # --lr-decay-iters "${NSTEP}"
                  --train-samples "${NSAMPLES}"
                  --lr-decay-samples "${NSAMPLES}"
                  --lr-decay-style cosine
                  --lr-warmup-fraction 0.002
                  --initial-loss-scale 65536
                  --bf16
                  # --load "$CHECKPOINT_PATH"
                  --pretrained-checkpoint "$CHECKPOINT_PATH"
                  --save "$SAVE_CKPT_PATH"
                  --save-interval 2000
                  --ckpt-format torch_dist
                  --dataloader-save "${SAVE_CKPT_PATH}/dataloader"

                  --ckpt-fully-parallel-load
                  --recompute-granularity full
                  --recompute-method uniform
                  --recompute-num-layers 4

                  # --async-save
                  --no-load-rng
                  --no-load-optim

                  --eval-iters 0

                  --no-check-for-nan-in-loss-and-grad
                  --cross-entropy-loss-fusion
                  --cross-entropy-fusion-impl 'te'
              )

              MODEL_PARALLEL_ARGS=(
                  --attention-backend flash
                  --pipeline-model-parallel-size "${PP}"
                  --tensor-model-parallel-size "${TP}"
                  --expert-model-parallel-size 8
                  --context-parallel-size 1
                  # --sequence-parallel
                  --use-distributed-optimizer
                  --cp-comm-type 'p2p'
                  --distributed-backend nccl
              )

              # FP8_ARGS=(
              #     --fp8-format 'e4m3'
              #     --fp8-recipe 'blockwise'
              #     --fp8-amax-history-len 1024 
              #     --fp8-amax-compute-algo 'max'
              #     --num-layers-at-start-in-bf16 1
              #     --num-layers-at-end-in-bf16 1
              # )

              LOGGING_ARGS=(
                  --log-interval 1
                  --tensorboard-dir "${TENSORBOARD_PATH}"
                  --tensorboard-log-interval 1
                  --tensorboard-queue-size 1000
                  --log-timers-to-tensorboard
                  --use-pytorch-profiler
                  --log-validation-ppl-to-tensorboard
                  --log-timers-to-tensorboard
                  --log-throughput
                  --log-params-norm
              )

              TM=$(date "+%Y-%m-%d_%H:%M:%S")
              logfile="${SAVE_CKPT_PATH}/run_${TM}_tp${TP}_pp${PP}_seqlen${SEQ_LEN}_mbs${MBS}_gbs${GBS}.log"

              # export OFFLINE_PACKED_DATA='1'
              # export OFFLINE_PACKING_VQA='1'
              export PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.72

              PYTHONPATH="$TRAINING_PATH:$MEGATRON_PATH" \
                  torchrun "${DISTRIBUTED_ARGS[@]}" \
                  "$TRAINING_PATH/vlm/train.py" \
                  "${MODEL_ARGS[@]}" \
                  "${MOE_ARGS[@]}" \
                  "${MLA_ARGS[@]}" \
                  "${DATA_ARGS[@]}" \
                  ${IMG_ARGS:+${IMG_ARGS[@]}} \
                  "${TRAINING_ARGS[@]}" \
                  "${MODEL_PARALLEL_ARGS[@]}" \
                  "${LOGGING_ARGS[@]}" \
                  2>&1 | tee "$logfile"
            env:
            - name: CUDA_DEVICE_MAX_CONNECTIONS
              value: "1"
            - name: NVTE_ALLOW_NONDETERMINISTIC_ALGO
              value: "1"
            - name: NVTE_FLASH_ATTN
              value: "1"
            - name: NCCL_DEBUG
              value: "INFO"
            - name: MEGATRON_LOGGING_LEVEL
              value: "20"
            - name: NCCL_IB_TIMEOUT
              value: "24"
            # NOTE(NAVER Cloud): Exclude ports mlx5_1, mlx5_0
            # It has been observed that NCCL may attempt cross-communication under heavy workloads
            # or with certain collective operations (e.g., all-gather).
            # 
            # To prevent this, we explicitly exclude interfaces not intended for RDMA computing.
            # mlx5_0, mlx5_1, mlx5_2~5 IB networks are not allowed to cross communication
            # 1. mlx5_0 is an ethernet link port for inband communication
            # 2. mlx5_1 is an IB port used for DDN
            # 3. mlx5_2~5 is IP ports for RDMA computing
            - name: NCCL_IB_HCA
              value: '^=mlx5_1,mlx5_0'
            # AF_INET6로 접근하는 것 자체는 막을 필요가 있음. 네이버클라우드는 ipv6를 완전히 꺼놓기 때문.
            #- name: NCCL_SOCKET_FAMILY
            #  value: AF_INET
            # NOTE(NAVER Cloud):
            # In typical scenarios, Gloo automatically falls back to IPv4 if IPv6 is not available.
            # However, in large-scale distributed training, this fallback mechanism can be triggered
            # at an extremely high frequency. Such repeated fallbacks can lead to the exhaustion
            # of system resources (e.g., file descriptors), which in turn may cause critical errors,
            # including segmentation faults. To mitigate this risk and ensure system stability,
            # explicitly force Gloo to use the AF_INET (IPv4) socket family.
            - name: GLOO_SOCKET_FAMILY
              value: AF_INET
            # NOTE(NAVER Cloud): For debugging when error occurs
            - name: TORCH_CPP_LOG_LEVEL
              value: '0'
            #- name: UB_SKIPMC
            #  value: '1'
            #- name: NCCL_COMM_BLOCKING
            #  value: '0'
            # NOTE(NAVER Cloud): Allocating sufficient CPU and memory resources is crucial 
            # to mitigate potential bottlenecks during GPU computations.
            # Requesting RDMA resources(rdma/hca_shared_devices_a) is necessary for the rdma-plugin
            # to automatically mount and enable Infiniband devices for the container.
            # VS Code/디버깅/런데부 등에서 관례적으로 쓰는 포트 노출(포워딩 용도)
            resources:
              limits:
                memory: "1Ti"
                cpu: 32
                nvidia.com/gpu: 8
                rdma/hca_shared_devices_a: 1
              requests:
                memory: "1Ti"
                cpu: 32
                nvidia.com/gpu: 8
                rdma/hca_shared_devices_a: 1
            volumeMounts:
            - mountPath: /dev/shm
              name: shared-memory
            - mountPath: "/mnt/data"
              name: training-data
              readOnly: true
            - mountPath: "/mnt/output2"
              name: training-output2
            - mountPath: "/mnt/output/ncai"
              name: training-output
              subPath: ncai
            - mountPath: "/mnt/output/pretraining_data"
              name: training-output
              subPath: pretraining_data
            - mountPath: "/mnt/output/pretraining_data_merged"
              name: training-output
              subPath: pretraining_data_merged
          volumes:
          - name: shared-memory
            emptyDir:
              medium: Memory
          - name: training-data
            persistentVolumeClaim:
              claimName: training-data
          - name: training-output
            persistentVolumeClaim:
              claimName: training-output
          - name: training-output2
            persistentVolumeClaim:
              claimName: training-output2
          - name: training-checkpoint
            persistentVolumeClaim:
              claimName: training-checkpoint